Suppliers/Suppliers.WebApp/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Suppliers.WebApp.Pages
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _db;
        [BindProperty]
        public Supplier Supplier {get;set;}
        public CreateModel(AppDbContext db)
        {
            _db=db;
        }
        public async Task<IActionResult> OnPostAsync(){
            if (!ModelState.IsValid)
            {
                return Page();
            }
_db.Suppliers.Add(Supplier);
await _db.SaveChangesAsync();

return RedirectToPage("/Index");
        }
    }
}

Suppliers/Suppliers.WebApp/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
namespace Suppliers.WebApp.Pages
{
    public class EditModel : PageModel
    {
       private readonly AppDbContext _db;
       [BindProperty]
       public Supplier Supplier { get; set; }
       public EditModel(AppDbContext db)
       {
           _db=db;
       }
       public async Task<IActionResult> OnGetAsync(int id){
           Supplier=await _db.Suppliers.FindAsync(id);
           if (Supplier==null)
           {
               return RedirectToAction("./Index");
           }
           return Page();
       }
       public async Task<IActionResult> OnPostAsync(){

           if (!ModelState.IsValid)
           {
               return Page();
           }
           _db.Attach(Supplier).State=EntityState.Modified;
         
           try
           {
               await  _db.SaveChangesAsync();
           }
           catch (DbUpdateConcurrencyException e)
           {
               
               throw new Exception($"Supplier {Supplier.Name} is not found!",e);
           }
             return RedirectToAction("./Index");
       }
    }
}

Suppliers/Suppliers.WebApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Suppliers.WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Suppliers/Suppliers.WebApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace Suppliers.WebApp.Pages
{
    public class IndexModel : PageModel
    {
       
       private readonly AppDbContext _db;
       public IList<Supplier> Suppliers {get;set;}
       public IndexModel(AppDbContext db)
       {
           _db=db;
       }
[BindProperty(SupportsGet=true)]
public string SearchString { get; set; }
public SelectList Names {get;set;}
public string Userselect { get; set; }
public async Task OnGetAsync(){
     var supps=from s in _db.Suppliers
     select s;
     if (!string.IsNullOrEmpty(SearchString))
     {
         supps=supps.Where(s=>s.Name.Contains(SearchString));
     }
     
    Suppliers=await _db.Suppliers.AsNoTracking().ToListAsync();
}
public async Task<IActionResult> OnPostDeleteAsync(int id){
    var supplier_find=await _db.Suppliers.FindAsync(id);
    if(supplier_find!=null){
        _db.Suppliers.Remove(supplier_find);
        await _db.SaveChangesAsync();
    }
    return RedirectToPage(); 
}


    }
}

Suppliers/Suppliers.WebApp/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Suppliers.WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Suppliers/Suppliers.WebApp/Pages/Create.cshtml
@page
@model Suppliers.WebApp.Pages.CreateModel
@{
    ViewData["Title"]= "Create";
}
<h2>Create</h2>

<form method="POST">
    <label for="fname">Enter your name:</label></br>
   <input asp-for="Supplier.Name" id="fname"/> </br>
   <div asp-validation-for="Supplier.Name"></div></br>
    <input type="submit" value="Save"/>
</form>

Suppliers/Suppliers.WebApp/Pages/Edit.cshtml
@page
@model Suppliers.WebApp.Pages.EditModel
@{
    ViewData["Title"]="Edit";
}
<h2>Edit @Model.Supplier.Id</h2>
<form method="POST">
    <input asp-for="Supplier.Id" type="hidden" />
    <label asp-for="Supplier.Name">Edit Name</label></br>
    <input asp-for="Supplier.Name"/>
    <div asp-validation-for="Supplier.Name"></div>
    <button type="submit" value="Edit"></button>
</form>

Suppliers/Suppliers.WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<form method="POST">
    <input type="text" asp-for ="SearchString"/>
    <input type="submit" value="Search"/>
</form>
<form method="POST">
    <table class="table">
        <thead>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var s in Model.Suppliers)
            {
                <tr>
                <td>@s.Id</td>
                <td>@s.Name</td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@s.Id">Edit</a>
                    <button type="submit" asp-page-handler="delete" asp-route-id="@s.Id">Delete</button>
                </td>
            </tr>
            }
            
        </tbody>
    </table>
</form>

Suppliers/Suppliers.WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Suppliers.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Suppliers.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Suppliers.WebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>